# Generated by cucumber-sinatra. (2014-10-03 12:19:00 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Ronin

class RoninWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RoninWorld.new
end
